### ISSUE TITLE
能够正常输出字符，但是生成的图片是空白图片

### ISSUE THREAD

**Issue by richenlin** [zxdong262/canvas-captcha#1]
如题

captchaStr没有问题
captchaImg是灰底的白图

**Comment by zxdong262** [comment]
系统缺少对应的字体导致的，安装相应的字体包或者换成系统里有的字体。

**Comment by richenlin** [comment]
mac ，firefox36

换了几种字体都不行，唉..

**Comment by zxdong262** [comment]
不是客户端缺少字体，而是服务器缺少字体

**Comment by zxdong262** [comment]
,font: '26px Arial'
这里把Arial 改成服务器系统里有的字体，或者安装一个包含Arial字体的字体包

**Comment by richenlin** [comment]
OK，谢谢，我试试

**Comment by zxdong262** [comment]
如果是ubuntu，试试
sudo apt-get install ttf-mscorefonts-installer

**Comment by richenlin** [comment]
安装字体后，已经成功了，谢谢
