### ISSUE TITLE
options.confusion = false not work

### ISSUE THREAD

**Issue by sophister** [zxdong262/canvas-captcha#3]
according to the [code](https://github.com/zxdong262/canvas-captcha/blob/master/index.js#L49), `options.confusion : false` not work.

```
,confusion: opts.confusion || defaults.confusion
```

**Comment by zxdong262** [comment]
right, fixed https://github.com/zxdong262/canvas-captcha/commit/4af6f11e1fe374afd2589beb45ae0c860a9b28ad and published new version
